In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.18.1


In [3]:
arr_list = np.array([1,2,3,4,5,6])
print(arr_list)

[1 2 3 4 5 6]


In [4]:
type(arr_list)

numpy.ndarray

In [5]:
arr_tuple = np.array((1,2,3,4,5,6))
print(arr_tuple)

[1 2 3 4 5 6]


In [6]:
type(arr_tuple)

numpy.ndarray

## Dimensions of an Array

In [7]:
arr_0d = np.array(26)
print(arr_0d)

26


In [8]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [9]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [10]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
print(arr_0d.ndim)
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

0
1
2
3


In [12]:
arr_5d = np.array([1,2,3], ndmin=5)
print(arr_5d)
print(arr_5d.ndim)

[[[[[1 2 3]]]]]
5


## Indexing

In [13]:
print(arr_1d[3])

4


In [14]:
print(arr_2d[0,2])

3


In [15]:
print(arr_3d[1,1,1])

11


In [16]:
print(arr_2d[-1,-1])

6


## Slicing


In [17]:
arr_2d[:-1]

array([[1, 2, 3]])

In [18]:
arr_3d[0:1][0:]

array([[[1, 2, 3],
        [4, 5, 6]]])

## Data types

In [19]:
arr_2d.dtype

dtype('int64')

In [20]:
mix_arr = np.array(['a','1','2'], dtype="i")

ValueError: invalid literal for int() with base 10: 'a'

In [21]:
float_arr = np.array([1.2,4.2,3.2,4.9])

int_arr = float_arr.astype('i')

in_arr = float_arr.astype('i')


print(float_arr)
print(int_arr)

[1.2 4.2 3.2 4.9]
[1 4 3 4]


## Copy vs View

In [22]:
arr_2d_copy = arr_2d.copy()
arr_2d_view = arr_2d.view()

In [23]:
print(arr_2d_copy)
print(arr_2d_view)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [24]:
print(arr_2d_copy.base)
print(arr_2d_view.base)

None
[[1 2 3]
 [4 5 6]]


## Shape of an array

In [25]:
print(arr_3d.shape)

(2, 2, 3)
