In [1]:
import numpy as np

In [3]:
print(np.__version__)

1.18.1


In [7]:
arr_list = np.array([1,2,3,4,5,6])
print(arr_list)

[1 2 3 4 5 6]


In [8]:
type(arr_list)

numpy.ndarray

In [6]:
arr_tuple = np.array((1,2,3,4,5,6))
print(arr_tuple)

[1 2 3 4 5 6]


In [9]:
type(arr_tuple)

numpy.ndarray

## Dimensions of an Array

In [16]:
arr_0d = np.array(26)
print(arr_0d)

26


In [17]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [18]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [28]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [21]:
print(arr_0d.ndim)
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

0
1
2
3


In [22]:
arr_5d = np.array([1,2,3], ndmin=5)
print(arr_5d)
print(arr_5d.ndim)

[[[[[1 2 3]]]]]
5


## Indexing

In [23]:
print(arr_1d[3])

4


In [25]:
print(arr_2d[0,2])

3


In [29]:
print(arr_3d[1,1,1])

11


In [31]:
print(arr_2d[-1,-1])

6
